from ursina import *
from figury import *
from board import *
from importlib import import_module
app = Ursina()
DirectionalLight(position=(1, 1, 3), shadows=True, color=color.white)
white_rook1 = Rook(color='white', position='a1')
white_rook2 = Rook(color='white', position='h1')
white_knight1 = Knight(color='white', position='b1')
white_knight2 = Knight(color='white', position='g1')
white_bishop1 = Bishop(color='white', position='c1')
white_bishop2 = Bishop(color='white', position='f1')
white_queen = Queen(color='white', position='d1')
white_king = King(color='white', position='e1')
white_pawn1 = Pawn(color='white', position='a2')
white_pawn2 = Pawn(color='white', position='b2')
white_pawn3 = Pawn(color='white', position='c2')
white_pawn4 = Pawn(color='white', position='d2')
white_pawn5 = Pawn(color='white', position='e2')
white_pawn6 = Pawn(color='white', position='f2')
white_pawn7 = Pawn(color='white', position='g2')
white_pawn8 = Pawn(color='white', position='h2')
black_rook1 = Rook(color='black', position='a8')
black_rook2 = Rook(color='black', position='h8')
black_knight1 = Knight(color='black', position='b8')
black_knight2 = Knight(color='black', position='g8')
black_bishop1 = Bishop(color='black', position='c8')
black_bishop2 = Bishop(color='black', position='f8')
black_queen = Queen(color='black', position='d8')
black_king = King(color='black', position='e8')
black_pawn1 = Pawn(color='black', position='a7')
black_pawn2 = Pawn(color='black', position='b7')
black_pawn3 = Pawn(color='black', position='c7')
black_pawn4 = Pawn(color='black', position='d7')
black_pawn5 = Pawn(color='black', position='e7')
black_pawn6 = Pawn(color='black', position='f7')
black_pawn7 = Pawn(color='black', position='g7')
black_pawn8 = Pawn(color='black', position='h7')
# Dodaj planszę szachową
board = load_board()
# Kamera
EditorCamera()

app.run()
